export const data = [
  {
    id: 1,
    image: "images/portfolio/1.png",
    url: "https://www.e-yug.com/",
    category: "Wordpress",
  },
  {
    id: 2,
    image: "images/portfolio/2.png",
    url: "http://maklaw.in/",
    category: "Wordpress",
  },
  {
    id: 3,
    image: "images/portfolio/3.png",
    url: "https://varunsrikanth.com/",
    category: "Wordpress",
  },
  {
    id: 4,
    image: "images/portfolio/4.png",
    url: "https://silversandhotels.com/",
    category: "Wordpress",
  },
  {
    id: 5,
    image: "images/portfolio/5.png",
    url: "https://tlhblogs.com/",
    category: "Wordpress",
  },
  {
    id: 6,
    image: "images/portfolio/6.png",
    url: "https://stoicuslegal.com/",
    category: "Wordpress",
  },
  {
    id: 7,
    image: "images/portfolio/7.png",
    url: "https://feeljoy.in/",
    category: "Wordpress",
  },
  {
    id: 8,
    image: "images/portfolio/8.png",
    url: "https://blog.refyne.co.in/",
    category: "Wordpress",
  },
  {
    id: 9,
    image: "images/portfolio/9.png",
    url: "https://obori.in/",
    category: "Wordpress",
  },
  {
    id: 10,
    image: "images/portfolio/10.png",
    url: "https://designical.in/",
    category: "Wordpress",
  },
  {
    id: 11,
    image: "images/portfolio/11.png",
    url: "http://promove.in/",
    category: "Wordpress",
  },
  {
    id: 12,
    image: "images/portfolio/12.png",
    url: "https://northtreeadvisory.com/",
    category: "Wordpress",
  },
  {
    id: 13,
    image: "images/portfolio/13.png",
    url: "https://www.rajivesumita.com/",
    category: "Wordpress",
  },
  {
    id: 14,
    image: "images/portfolio/14.png",
    url: "https://farmnatural.in/",
    category: "Wordpress",
  },
  {
    id: 15,
    image: "images/portfolio/15.png",
    url: "https://satellitechannel.net/",
    category: "Wordpress",
  },
  {
    id: 16,
    image: "images/portfolio/16.png",
    url: "https://www.luckies.co.uk/",
    category: "Wordpress",
  },
  {
    id: 17,
    image: "images/portfolio/17.png",
    url: "https://www.braddicksholidaycentre.co.uk/",
    category: "Wordpress",
  },
  {
    id: 18,
    image: "images/portfolio/18.png",
    url: "https://www.scratchmap.com/",
    category: "Wordpress",
  },
  {
    id: 19,
    image: "images/portfolio/19.png",
    url: "https://prospanceinc.com/",
    category: "Wordpress",
  },
  {
    id: 20,
    image: "images/portfolio/20.png",
    url: "https://www.networkersguru.com/",
    category: "Wordpress",
  },
  {
    id: 21,
    image: "images/portfolio/21.png",
    url: "https://vysmo.com/",
    category: "Wordpress",
  },
  {
    id: 22,
    image: "images/portfolio/22.png",
    url: "http://flightsdaddy.com/",
    category: "Wordpress",
  },
  {
    id: 23,
    image: "images/portfolio/23.png",
    url: "https://budgetpharmacyfiji.com",
    category: "Wordpress",
  },
  {
    id: 24,
    image: "images/portfolio/24.png",
    url: "https://www.pyarimaafoundation.org/",
    category: "Wordpress",
  },
  {
    id: 25,
    image: "images/portfolio/25.png",
    url: "http://blognotes.in/",
    category: "Wordpress",
  },
  {
    id: 26,
    image: "images/portfolio/26.png",
    url: "https://berozgarnews.com/dev/",
    category: "Wordpress",
  },
  {
    id: 27,
    image: "images/portfolio/27.png",
    url: "https://www.ip4networkers.com/",
    category: "Wordpress",
  },
  {
    id: 28,
    image: "images/portfolio/28.png",
    url: "http://www.useducentre.com/",
    category: "HTML",
  },
  {
    id: 29,
    image: "images/portfolio/29.png",
    url: "https://www.ncomputing.com/",
    category: "HTML",
  },
  {
    id: 30,
    image: "images/portfolio/30.png",
    url: "https://refyne.co.in/",
    category: "HTML",
  },
  {
    id: 31,
    image: "images/portfolio/31.png",
    url: "https://www.bhartipay.com/",
    category: "HTML",
  },
  {
    id: 32,
    image: "images/portfolio/32.png",
    url: "http://transitplusglobal.com/",
    category: "HTML",
  },
  {
    id: 33,
    image: "images/portfolio/33.png",
    url: "https://www.firstlease.in/",
    category: "HTML",
  },
  {
    id: 34,
    image: "images/portfolio/34.png",
    url: "https://vidboard.ai/",
    category: "HTML",
  },
  {
    id: 35,
    image: "images/portfolio/35.png",
    url: "https://kodenative.com/",
    category: "HTML",
  },
  {
    id: 36,
    image: "images/portfolio/36.png",
    url: "http://policybol.com/",
    category: "HTML",
  },
  {
    id: 37,
    image: "images/portfolio/37.png",
    url: "https://react-store-comfy.netlify.app/",
    category: "React",
  },
  {
    id: 38,
    image: "images/portfolio/38.png",
    url: "https://ashish-bhardwaj.online/",
    category: "React",
  },
  {
    id: 39,
    image: "images/portfolio/39.png",
    url: "https://birthday-ab.netlify.app/",
    category: "React",
  },
  {
    id: 40,
    image: "images/portfolio/40.png",
    url: "https://tours-ab.netlify.app/",
    category: "React",
  },
  {
    id: 41,
    image: "images/portfolio/41.png",
    url: "https://lorem-ipsum-ab.netlify.app/",
    category: "React",
  },
  {
    id: 42,
    image: "images/portfolio/42.png",
    url: "https://jobs-ab.netlify.app/",
    category: "React",
  },
  {
    id: 43,
    image: "images/portfolio/43.png",
    url: "https://markdown-ab.netlify.app/",
    category: "React",
  },
  {
    id: 44,
    image: "images/portfolio/44.png",
    url: "https://www.faceswingers.com/",
    category: "Social Engine",
  },
  {
    id: 45,
    image: "images/portfolio/45.png",
    url: "https://lets.live/",
    category: "Social Engine",
  },
  {
    id: 46,
    image: "images/portfolio/46.png",
    url: "http://onskedule.com/",
    category: "Social Engine",
  },
  {
    id: 47,
    image: "images/portfolio/47.png",
    url: "https://twitterclone.socialnetworking.solutions/",
    category: "Social Engine",
  },
  {
    id: 48,
    image: "images/portfolio/48.png",
    url: "https://linkdinclone.socialnetworking.solutions/",
    category: "Social Engine",
  },
  {
    id: 49,
    image: "images/portfolio/49.png",
    url: "https://instaclone.socialnetworking.solutions/",
    category: "Social Engine",
  },
  {
    id: 50,
    image: "images/portfolio/50.png",
    url: "https://companytheme.socialnetworking.solutions/",
    category: "Social Engine",
  },
  {
    id: 51,
    image: "images/portfolio/51.png",
    url: "https://sportztheme.socialnetworking.solutions/",
    category: "Social Engine",
  },
  {
    id: 52,
    image: "images/portfolio/52.png",
    url: "https://spectromediatheme.socialnetworking.solutions/",
    category: "Social Engine",
  },
  {
    id: 53,
    image: "images/portfolio/53.png",
    url: "https://datingtheme.socialnetworking.solutions/",
    category: "Social Engine",
  },
  {
    id: 54,
    image: "images/portfolio/54.png",
    url: "https://materialtheme.socialnetworking.solutions/",
    category: "Social Engine",
  },
  {
    id: 55,
    image: "images/portfolio/55.png",
    url: "https://newfbclone.socialnetworking.solutions/",
    category: "Social Engine",
  },
  {
    id: 56,
    image: "images/portfolio/56.png",
    url: "https://shopcontra.com/",
    category: "Social Engine",
  },
  {
    id: 57,
    image: "images/portfolio/57.png",
    url: "https://disastersites.com/",
    category: "Social Engine",
  },
  {
    id: 58,
    image: "images/portfolio/58.png",
    url: "https://www.artistter.com/",
    category: "Social Engine",
  },
  {
    id: 59,
    image: "images/portfolio/59.png",
    url: "https://www.totalprestigemagazine.com/",
    category: "Social Engine",
  },
  {
    id: 60,
    image: "images/portfolio/60.png",
    url: "https://courses.socialnetworking.solutions/",
    category: "Social Engine",
  },
  {
    id: 61,
    image: "images/portfolio/61.png",
    url: "https://utubeclone.socialnetworking.solutions/",
    category: "Social Engine",
  },
];

